CREATE TABLE dbo.Ariculos
(
	ID INT IDENTITY PRIMARY KEY,
	OrdenId INT NOT NULL FOREIGN KEY REFERENCES Orden(ID),
	SKU INT NOT NULL,
	Precio NUMERIC(10,2) NOT NULL,
	Cantidad NUMERIC(10,2) NOT NULL,
	Nombre VARCHAR(50) NOT NULL,
	Subtotal NUMERIC(10,2) NOT NULL,
	TotalImpuestos NUMERIC(10,2) NOT NULL,
	Total NUMERIC(10,2) NOT NULL
)
