CREATE TABLE dbo.Cliente
(
	ID INT IDENTITY PRIMARY KEY,
	OrdenId INT NOT NULL FOREIGN KEY REFERENCES Orden(ID),
	Nombre VARCHAR(50) NOT NULL,
	Apellido VARCHAR(50) NOT NULL,
	Email VARCHAR(30) NOT NULL,
	Telefono VARCHAR(15) NOT NULL,
	Direccion VARCHAR(100) NOT NULL
)